# Generated by Django 4.2.20 on 2025-04-10 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('A', 'Action'), ('B', 'Biography'), ('C', 'Comedy'), ('D', 'Drama'), ('E', 'Western'), ('F', 'Fantasy'), ('G', 'Crime'), ('H', 'Horror'), ('I', 'Animation'), ('J', 'Adventure'), ('K', 'K-Drama'), ('L', 'History'), ('M', 'Musical'), (' N', 'None'), ('O', 'Other'), ('P', 'Documentary'), ('R', 'Romance'), ('S', 'Sport'), ('SF', 'Sci-Fi'), ('T', 'Thriller'), ('W', 'War'), ('X', 'Family'), ('Y', 'Mystery'), ('Z', 'Short Film')], max_length=3)),
                ('year', models.DateField(verbose_name='Release Year')),
                ('description', models.TextField(max_length=500)),
                ('actors', models.ManyToManyField(to='my_app.actor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
